server:
  servlet:
    context-path: /WateringCan
  port: 8081
    
spring:  application:    name: watering-can
    
    
logging:
  level:
    root: INFO
    com: 
      marcosolina: DEBUG
      
com:
  marcosolina:
    wateringcan:
      arduino:
        commands:
          port: 85
        discovery:
          head-message: WCAN
          port: 90
      pump:
        mlpersecond: 30